apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-drax
  namespace: carbon
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pratjainvmw/bookstore-app
    targetRevision: main
    path: kubernetes/overlays/drax
  destination:
    name: drax            # must match: argocd cluster add <ctx> --name drax
    namespace: bookstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff: { duration: 5s, factor: 2, maxDuration: 3m }
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
